version: '3.8'

services:
  backend:
    image: alifarhan3311/visionpro-backend:latest
    container_name: visionpro-backend
    restart: always
    networks:
      - vision-pro
    environment:
      - MONGO_URI=mongodb+srv://alifarhan1531_db_user:azadar3311@cluster0.57zf8ot.mongodb.net/
      - JWT_SECRET=mobilesentrix_super_secret_key  
    volumes:
      - vision_pro_backup_uploads:/app/uploads

 frontend:
    image: alifarhan3311/visionpro-frontend:latest
    container_name: visionpro-frontend
    ports:
      - "8083:80"
    networks:
      - vision-pro
    volumes:
      - vision_pro_backup_uploads:/var/www/uploads:ro
    depends_on:
      - backend

networks:
  vision-pro:
    driver: bridge

volumes:
  vision_pro_backup_uploads:
